openapi: 3.0.0
info:
  title: Payment API
  description: API for user authentication, payments, and transaction management.
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Development Server

paths:
  /health:
    get:
      summary: Check API health
      tags:
        - System
      responses:
        '200':
          description: Service is running correctly
          content:
            application/json:
              schema:
                type: string
                example: "Healthy"

  /api/v1/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/MultipleValidationErrorResponse'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserExistsErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid credentials or validation error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CredentialsErrorResponse'
                  - $ref: '#/components/schemas/ValidationErrorResponse'
                  - $ref: '#/components/schemas/MultipleValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/transactions/getTransactionByIdStateResource:
    get:
      summary: Get transaction details by ID
      tags:
        - Transactions
      security:
        - BearerAuth: []
      parameters:
        - name: transactionId
          in: query
          required: true
          description: Unique identifier of the transaction
          schema:
            type: string
            format: uuid
            example: "4aa93b80-577f-11eb-add8-83fc90ae146c"
      responses:
        '200':
          description: Transaction details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  description:
                    type: string
                    example: "Success"
                  detail:
                    type: object
                    properties:
                      respuest:
                        type: object
                        properties:
                          id_establecimiento:
                            type: integer
                            example: 555
                          monto:
                            type: string
                            example: "12.00"
                          fecha_transaccion:
                            type: string
                            format: date-time
                            example: "2025-03-23T22:00:20.000Z"
                          descripcion:
                            type: string
                            example: "Descripcion del pago"
                          id_transaccion:
                            type: string
                            example: "f9819772-295b-4319-8ab0-998a17ea7460"
                          valor_catalogo_estado:
                            type: string
                            example: "PAG"
                          respuesta:
                            type: string
                            nullable: true
                          voucher:
                            type: string
                            example: "514839-250323-333476"
                          adquiriente:
                            type: string
                            example: "DINERS"
                          valor_base0:
                            type: string
                            example: "2.00"
                          valor_base12:
                            type: string
                            example: "8.70"
                          valor_iva:
                            type: string
                            example: "1.30"
                          numero_lote:
                            type: string
                            example: "250323"
                          propina:
                            type: string
                            nullable: true
                          banco:
                            type: string
                            example: "GUAYAQUIL"
                          emisor_tarjeta:
                            type: string
                            example: "BANCO DE GUAYAQUIL, S.A."
                          numero_cuotas:
                            type: integer
                            example: 0
                          proveedor_servicio_pago:
                            type: string
                            example: "datafast"
                          tipo_credito:
                            type: string
                            example: "00"
                          meses_gracia:
                            type: integer
                            example: 0
                          interes:
                            type: integer
                            example: 0
                          valor_interes:
                            type: string
                            example: "0.00"
                          extras:
                            type: string
                            nullable: true
                          marca:
                            type: string
                            example: "VISA"
                          catalogos:
                            type: object
                            properties:
                              nombre_catalogo:
                                type: string
                                example: "Aprobada"
                          cliente:
                            type: object
                            properties:
                              nombres:
                                type: string
                                example: "JOHN DOE"
                              numero_identificacion:
                                type: string
                                example: "1754199055"
                          detalle:
                            type: object
                            properties:
                              numero_tarjeta:
                                type: string
                                example: "4540 63XX XXXX 8783"
                          items:
                            type: array
                            items:
                              type: object
                          mid:
                            type: string
                            example: "7400000001"
                          tid:
                            type: string
                            example: "FP230223"
                          adquirente:
                            type: string
                            example: "DINERS"
                          informacionTarjeta:
                            type: object
                            properties:
                              mesExpiracion:
                                type: string
                                example: "04"
                              anioExpiracion:
                                type: string
                                example: "2025"
                          tipoPago:
                            type: string
                            example: "tarjeta"
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
        '404':
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - name
        - surname
        - email
        - password
      properties:
        name:
          type: string
          example: "John"
        surname:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        password:
          type: string
          format: password
          minLength: 8
          example: "supersecurepassword"

    RegisterResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        password:
          type: string
          format: password
          example: "supersecurepassword"

    LoginResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "John"
        surname:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

    TransactionResponse:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          example: "4aa93b80-577f-11eb-add8-83fc90ae146c"
        status:
          type: string
          example: "Completed"
        amount:
          type: number
          format: float
          example: 100.50
        currency:
          type: string
          example: "USD"
        createdAt:
          type: string
          format: date-time
          example: "2024-03-22T10:30:00Z"

    UserExistsErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "User already exists"

    ValidationErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              example: "\"surname\" must be a string"
            path:
              type: string
              example: "surname"

    MultipleValidationErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "email"
              message:
                type: string
                example: "Email is required"

    CredentialsErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid email or password"

    UnauthorizedErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Unauthorized - Token required or invalid"

    NotFoundErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 404
        message:
          type: string
          example: "Transacción no encontrada."

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Internal server error"
